### ISSUE TITLE
Gradient for getindex

### ISSUE THREAD

**Issue by DhairyaLGandhi** [SomTambe/DiffImages.jl#10]
https://github.com/SomTambe/DiffImages.jl/blob/6937f982febbdd6dbe963cca562b50f66c45589b/src/geometry/adjoints.jl#L76

Notice that the output gradient does not depend on the `δ`, which does not seem correct.

**Comment by SomTambe** [comment]
Yeah you were correct, it's a mistake.
It should be in the format `δ * gr` .
But here, I had a doubt.
`δ` is in the form of `NamedTuple(:r,:g,:b)` when we give it an `RGB` image. how would the multiplication operation be defined in this case, if gr is a `SVector` consisting of 2 elements, each being `RGB` ?
I think since the gradients propagate channelwise, it will be channelwise multiplication of `δ` and `gr` elements.

What do you think @johnnychen94?

**Comment by DhairyaLGandhi** [comment]
I would imagine you could construct an RGB from delta and use ColorVectorSpace to handle the multiplication.

**Comment by DhairyaLGandhi** [comment]
Which is channelwise multiplication in this case, but may not be generically true, for colorspaces whose fields are not orthogonal. But that's just my guess.

**Comment by SomTambe** [comment]
Well I used hadamard `⊙` from CVS. I made these changes -
```julia
Zygote.@adjoint function ImageTransformations._getindex(A::AbstractExtrapolation, x)
    y = A(Tuple(x)...)
    function ∇(δ)
        gr = Interpolations.gradient(A, Tuple(x)...)
        if !(typeof(δ) <: Number)
            δ = eltype(gr)(δ...)
            gr = δ .⊙ gr
        else
            gr = δ .* gr
        end
        return (nothing, (gr,))
    end
    return (y, ∇)
end
```
There still seems to be some difference in the gradients -
```julia
julia> Zygote.gradient(h) do trfm
           y = warp(src3, trfm, 0.0)
           y = mseloss(y, tgt3)
           y
       end[1].H
3×3 Matrix{Float64}:
 35976.8        76976.4         701.519
     1.0566e5   61267.0        1342.3
    -1.17905e7     -1.46389e7    -1.42039e5

julia> grad(central_fdm(5,1),f,h)[1].H
3×3 SMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
 50848.0         1.60798e5  701.662
     1.82618e5   1.16586e5  852.918
    -8.85505e6  -1.70292e7   -3.04226e5
```
`f` is the same function written in the `Zygote.gradient` part. `mseloss` is literally the L2 loss.

**Comment by SomTambe** [comment]
I experimented a bit more, and I got this -
```julia
julia> zygm = Zygote.gradient(h) do trfm
           y = warp(src3, trfm, 0.0)
           y = mseloss(y, tgt3)
           y
       end[1].H
3×3 Matrix{Float64}:
 35976.8        76976.4         701.519
     1.0566e5   61267.0        1342.3
    -1.17905e7     -1.46389e7    -1.42039e5

julia> fdm = grad(central_fdm(2,1),f,h)[1].H
3×3 SMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
 35976.8        76976.4         701.519
     1.0566e5   61267.0        1342.3
    -1.17905e7     -1.46389e7    -1.42039e5

julia> zygm - fdm
3×3 SMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
  0.0014415     0.00132396  -0.000471868
  0.000241908  -0.00309845   0.000104416
 -0.0023831    -0.0184508    0.00364473
```
The docs for FiniteDifferences [here](https://juliadiff.org/FiniteDifferences.jl/latest/pages/api/#FiniteDifferences.central_fdm) show that the first argument denotes the number of grid points, but I would like to read more about it.
Anyways, now the finite differences methods gradient is literally equal to the Zygote gradient.

**Comment by DhairyaLGandhi** [comment]
Would you be able to say more about the experimentation?

**Comment by DhairyaLGandhi** [comment]
Have we tried training with finite differences?

**Comment by SomTambe** [comment]
>Would you be able to say more about the experimentation?

Nothing! I just changed from 5th order central method to 2nd order central method, and the gradients are equal now!

**Comment by SomTambe** [comment]
Another update:
`central_fdm(5, 1; adapt=2, max_range=1e-4)` also works pretty good, but still cannot beat `central_fdm(2,1)`.

**Comment by johnnychen94** [comment]
Since there will be a new alternative PR to #7 I'd suggest write new adjoints using `ChainRulesCore` and then test every `rrule` with https://github.com/JuliaDiff/ChainRulesTestUtils.jl

**Comment by johnnychen94** [comment]
As a minimal example, we could have early identified this issue if we've checked this:

```julia
using ChainRules, ChainRulesTestUtils
using ImageTransformations, Interpolations

function ChainRules.rrule(::typeof(ImageTransformations._getindex), A::AbstractExtrapolation, x)
    y = A(Tuple(x)...)
    function ∇(δ)
        gr = Interpolations.gradient(A, Tuple(x)...)
        return (ChainRules.ZeroTangent(), (gr,))
    end
    return (y, ∇)
end

A = extrapolate(interpolate(Float64[1, 4, 2], BSpline(Linear())), 0.0)
rrule(ImageTransformations._getindex, A, 1.5)

test_rrule(ImageTransformations._getindex, A, 1.5) # this errors
```

Once again, it's a good practice to incrementally write tests for every piece of the entire pipeline.

**Comment by SomTambe** [comment]
This seems to be a nice way to go with testing. I shall convert the tests to these types which use `test_rrule` and update you with it.

**Comment by SomTambe** [comment]
Yeah I was getting similar errors - 
```julia
```

**Comment by SomTambe** [comment]
Yeah I was getting similar errors, not sure how acceptable something like this is -
```julia
...
  Got exception outside of a @test
  InexactError: Int64(2.99)
...
```
Even in other cases - 
```julia
  Got exception outside of a @test
  InexactError: Int64(186.99)
```

**Comment by SomTambe** [comment]
I already read the stacktraces. The problem is encountered in the `FiniteDifferences.to_vec` function, which does not work very well with Integers (and structs with them). Nevertheless, the issue for us had gotten resolved, since I wrote the tests myself instead of using `ChainRulesTestUtils`; there should be a look into why tests with Interpolations fail with CRTU, and how to resolve them, but I guess that is beyond the scope of what I am doing. I may pick that issue later on CRTU, and  provide a solution, but for now, we are sorted.

If you still want the stacktraces, please let me know, I shall be happy to provide them.
