### ISSUE TITLE
Add docs, demo and rectify signs

### ISSUE THREAD

**Issue by SomTambe** [SomTambe/DiffImages.jl#18]
We need a demo for the homography training example. This should be added as a part of the docs.
We currently have a sign problem. The gradients calculated by AD and the hand written gradients have exactly opposite signs. There needs to be a fix for this, and I'll have a better idea where the sign is going wrong when I write the demo using DiffImages. I already checked the individual gradients in the pipeline - there was no problem with them and the tests for all the rules are passing. There is a small quirk, and that I will figure out.

- [x] Add demo to the docs
- [ ] Rectify the sign problem.

**Comment by DhairyaLGandhi** [comment]
Last piece of the puzzle for #12 ?

**Comment by SomTambe** [comment]
Yes, last piece of the puzzle.
